language: java
install: true
branches:
  only:
  - master
jdk:
- oraclejdk8
before_script:
- npm install --save github-remove-all-releases
script:
- gradle build
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then node cleanup-releases.js; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh cleanup-tags.sh; fi'
notifications:
  email: false
